# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: vln_r2r
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat/dataset/vln: mp3d_r2r
  - /habitat/task/lab_sensors:
    - gps_sensor
    - compass_sensor
  - _self_

habitat:
  environment:
    max_episode_steps: 150
    iterator_options:
      max_scene_repeat_steps: 50000
      shuffle: False
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 512
            height: 512
            hfov: 90
          depth_sensor:
            width: 256
            height: 256
            hfov: 90
            min_depth: 0.0
            max_depth: 10.0
    forward_step_size: 0.25
    turn_angle: 15
    habitat_sim_v0:
      gpu_device_id: 0
  task:
    measurements:
      distance_to_goal:
        type: DistanceToGoal
        distance_to: POINT
      success:
        type: Success
        success_distance: 3.0
      spl:
        type: SPL
      oracle_success:
        type: OracleSuccess
        # success_distance: 3.0
      oracle_navigation_error:
        type: OracleNavigationError
        
  dataset:
    type: R2RVLN-v1
    split: val_seen
    scenes_dir: data/scene_datasets/
    data_path: data/datasets/r2r/{split}/{split}.json.gz